PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
PubkeyAcceptedAlgorithms ssh-ed25519
HostbasedAuthentication no
HostKeyAlgorithms ssh-ed25519
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org
Ciphers aes128-gcm@openssh.com,chacha20-poly1305@openssh.com
Compression no
RekeyLimit 16G
UseDNS no
GSSAPIAuthentication no
LoginGraceTime 10
